configs = {
    'country': 'AT',
    'ntp_host': 'pool.ntp.org',
    'gmt_offset': 1,
    'auto_summertime': True,
    'disable_wifi_powersavingmode': True,
    'api_port': 80,
    'hostname': 'tcs2fhem',
    'displayoff': 5,
    'log_incoming_bus_messages': True,
    'log_housekeeping_days': 7,
    'frontdoor_ringing_message': 'abc',
    'door_ringing_message': 'cdf',
    'door_trigger_message': 'aaa',
    'light_trigger_message': 'bbb',
    'api_client_ip': '10.0.3.5',
    }