configs = {
    'country': 'AT',
    'ntp_host': 'pool.ntp.org',
    'gmt_offset': 1,
    'auto_summertime': True,
    'disable_wifi_powersavingmode': True,
    'api_port': 80,
    'hostname': 'tcs2fhem',
    'displayoff': 5,
    'log_incoming_bus_messages': True,
    'log_housekeeping_days': 7,
    'frontdoor_ringing_message': [1, 2, 2, 0, 0, 1],
    'door_ringing_message': [1, 2, 2, 0, 0, 2],
    'door_trigger_message': [1, 2, 2, 0],
    'light_trigger_message': [1, 2, 2, 1],
    'tcs_message': [1, 2, 2, 0, 1],
    'api_client_ip': '10.0.3.5',
    'fhem_door_ringed': 'http://fhem-server:8086/fhem?cmd=set%20TCS_Door%20ringed&XHR=1',
    'fhem_frontdoor_ringed': 'http://fhem-server:8086/fhem?cmd=set%20TCS_FrontDoor%20ringed&XHR=1',
    }
